name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make this better? Let us know!

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see added or changed?
      placeholder: Describe your idea...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this help your workflow?
      placeholder: This would help me...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part would this affect?
      options:
        - Roblox Plugin
        - MCP Server
        - New Tool/Method
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this feature
